# Generated by Django 5.2 on 2025-04-28 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.studentprofile')),
            ],
        ),
    ]
