# Generated by Django 5.2 on 2025-04-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='students',
            field=models.ManyToManyField(through='attendance.Attendance', to='attendance.studentprofile'),
        ),
    ]
