# Generated by Django 5.2 on 2025-04-30 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_lecture_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='university_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
