# Generated by Django 5.2 on 2025-05-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_lecture_date_alter_lecture_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='access_key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='key_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
