# Generated by Django 5.2 on 2025-05-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_lecture_access_key_lecture_key_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
