# Generated by Django 5.2 on 2025-05-11 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_department_remove_group_faculty_group_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='department_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.department'),
        ),
    ]
