# Generated by Django 5.2 on 2025-05-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_teacherprofile_department_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='department',
        ),
    ]
